services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8001
    volumes:
      - .:/users-microservice
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: users_microservice
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "33063:3306"
volumes:
  users_data: